'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),url=require('url');
const ROOT=path.resolve(__dirname,'..'),DB_FILE=path.join(__dirname,'db.json'),PORT=Number(process.env.PORT||8080);
const CONFIG={deposit:{network:'TRC20',currency:'USDT',address:'TFLkxFWGRQqS8rdiEbPFPQwRbke7fssf5c',minAmount:100},withdrawal:{network:'TRC20',currency:'USDT',minAmount:10},plans:{1:{amount:100,rate:1.1},2:{amount:200,rate:1.2},3:{amount:300,rate:1.3},4:{amount:400,rate:1.4},5:{amount:500,rate:1.5}},sessionMinutes:30,maxBodyBytes:2e6};
const ADMIN_EMAIL=(process.env.CAPITAL_ADMIN_EMAIL||'admin@capital.local').trim().toLowerCase();
const ADMIN_PASSWORD=process.env.CAPITAL_ADMIN_PASSWORD||'ChangeMe123!';
function now(){return new Date().toISOString()}
function id(p){return p+'-'+Date.now().toString(36)+'-'+crypto.randomBytes(4).toString('hex')}
function email(v){return String(v||'').trim().toLowerCase()}
function initial(){return {version:2,users:[],deposits:[],withdrawals:[],sessions:[],adminSessions:[],announcements:[],activities:[],settings:{adminName:'Administrator',timezone:'Asia/Kabul',deposit:{...CONFIG.deposit,qrData:''}},adminManagers:[],meta:{createdAt:now()}}}
function db(){if(!fs.existsSync(DB_FILE))save(initial());const d=JSON.parse(fs.readFileSync(DB_FILE,'utf8'));d.users??=[];d.deposits??=[];d.withdrawals??=[];d.sessions??=[];d.adminSessions??=[];d.announcements??=d.adminAnnouncements??[];d.activities??=[];d.settings??=initial().settings;d.settings.deposit??={...CONFIG.deposit,qrData:''};d.adminManagers??=[];return d}
function save(x){const t=DB_FILE+'.tmp';fs.writeFileSync(t,JSON.stringify(x,null,2));fs.renameSync(t,DB_FILE)}
function passwordHash(p,s=crypto.randomBytes(16).toString('hex')){return `scrypt$${s}$${crypto.scryptSync(String(p),s,64).toString('hex')}`}
function verifyPassword(p,stored){const a=String(stored||'').split('$');if(a.length!==3)return false;const got=crypto.scryptSync(String(p),a[1],64).toString('hex');return crypto.timingSafeEqual(Buffer.from(got,'hex'),Buffer.from(a[2],'hex'))}
function tokenHash(t){return crypto.createHash('sha256').update(t).digest('hex')}
function sanitize(u){if(!u)return null;const x={...u};delete x.passwordHash;return x}
function referralId(users){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';let v;do{v='CAP'+Array.from({length:5},()=>alphabet[crypto.randomInt(alphabet.length)]).join('')}while(users.some(u=>u.referralId===v));return v}
function cookies(req){const o={};for(const p of String(req.headers.cookie||'').split(';')){const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return o}
function setCookie(name,v,maxAge){return `${name}=${encodeURIComponent(v)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}`}
function send(res,status,data,extra={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY',...extra});res.end(JSON.stringify(data))}
function ok(res,data,extra={}){send(res,200,{data},extra)}function fail(res,s,c,detail){send(res,s,{code:c,...(detail?{detail}: {})})}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>CONFIG.maxBodyBytes)reject(Error('BODY_TOO_LARGE'))});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{reject(Error('INVALID_JSON'))}});req.on('error',reject)})}
function userAuth(req,D){const raw=cookies(req).capital_session;if(!raw)return null;const s=D.sessions.find(x=>x.tokenHash===tokenHash(raw)&&new Date(x.expiresAt)>new Date());if(!s)return null;s.lastActiveAt=now();return D.users.find(u=>u.id===s.userId)||null}
function adminAuth(req,D){const raw=cookies(req).capital_admin_session;if(!raw)return null;const s=D.adminSessions.find(x=>x.tokenHash===tokenHash(raw)&&new Date(x.expiresAt)>new Date());if(!s)return null;s.lastActiveAt=now();return s}
function requireUser(req,res,D){const u=userAuth(req,D);if(!u){fail(res,401,'UNAUTHENTICATED');return null}return u}
function requireAdmin(req,res,D){const a=adminAuth(req,D);if(!a){fail(res,401,'ADMIN_UNAUTHENTICATED');return null}return a}
function amount(v){const n=Number(v);return Number.isFinite(n)&&n>0?n:null}
function wallet(v){return /^T[1-9A-HJ-NP-Za-km-z]{33}$/.test(String(v||'').trim())}
function activity(D,action,details){D.activities.unshift({id:id('ACT'),action,details,createdAt:now()});D.activities=D.activities.slice(0,500)}
function dashboard(u,D){const pending=D.withdrawals.filter(w=>w.userId===u.id&&w.status==='pending').reduce((s,w)=>s+Number(w.amount),0);return {investedCapital:+(u.investedCapital||0),dailyProfit:+(u.dailyProfit||0),teamProfit:+(u.teamProfit||0),totalProfit:+(u.totalProfit||0),available:Math.max(0,+(u.available||0)-pending),totalWithdrawals:+(u.totalWithdrawals||0),balance:+(u.balance||0),activePlan:u.activePlan||null,notificationReadIds:u.notificationReadIds||[]}}
function team(u,D){const direct=D.users.filter(x=>x.referredBy===u.referralId),seen=new Set(),q=direct.map(x=>x.id);while(q.length){const id=q.shift();if(seen.has(id))continue;seen.add(id);const c=D.users.find(x=>x.id===id);if(c)D.users.filter(x=>x.referredBy===c.referralId).forEach(x=>q.push(x.id))}return {directMembers:direct.length,teamMembers:seen.size}}
function notifications(u,D){const read=new Set(u.notificationReadIds||[]);const ws=D.withdrawals.filter(w=>w.userId===u.id&&['completed','approved','success','rejected'].includes(String(w.status).toLowerCase())).map(w=>{const st=String(w.status).toLowerCase(),nid='withdrawal:'+w.id+':'+st;return{id:nid,kind:'withdrawal',status:st==='rejected'?'rejected':'success',title:st==='rejected'?'Withdrawal request rejected':'Withdrawal request completed',body:st==='rejected'?(w.rejectReason||'Your withdrawal request was rejected.'):`Withdrawal ${Number(w.amount).toFixed(2)} USDT was processed successfully.`,createdAt:w.processedAt||w.createdAt,read:read.has(nid)}});const as=D.announcements.filter(x=>!x.userId||x.userId===u.id).map(x=>({id:'announcement:'+x.id,kind:'admin',status:'info',title:x.title,body:x.body,createdAt:x.createdAt,read:read.has('announcement:'+x.id)}));return [...ws,...as].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
async function api(req,res){const D=db(),p=url.parse(req.url).pathname;try{
 if(req.method==='GET'&&p==='/api/config'){return ok(res,{deposit:{network:D.settings.deposit.network||CONFIG.deposit.network,currency:CONFIG.deposit.currency,address:D.settings.deposit.address||CONFIG.deposit.address,minAmount:CONFIG.deposit.minAmount,qrData:D.settings.deposit.qrData||''},withdrawal:CONFIG.withdrawal,plans:CONFIG.plans,sessionMinutes:CONFIG.sessionMinutes})}
 if(req.method==='POST'&&p==='/api/auth/register'){const x=await body(req),em=email(x.email);if(!em||!String(x.password||'').match(/^.{8,128}$/))return fail(res,400,'INVALID_PASSWORD');if(D.users.some(u=>email(u.email)===em))return fail(res,409,'EMAIL_EXISTS');const u={id:id('USR'),referralId:referralId(D.users),name:String(x.name||'').trim(),family:String(x.family||'').trim(),email:em,passwordHash:passwordHash(x.password),status:'active',createdAt:now(),lastLoginAt:now(),wallet:'',referredBy:String(x.referredBy||'').trim(),balance:0,available:0,investedCapital:0,dailyProfit:0,teamProfit:0,totalProfit:0,totalWithdrawals:0,activePlan:null,notificationReadIds:[]};D.users.push(u);const raw=crypto.randomBytes(32).toString('hex');D.sessions.push({tokenHash:tokenHash(raw),userId:u.id,createdAt:now(),expiresAt:new Date(Date.now()+CONFIG.sessionMinutes*60000).toISOString(),lastActiveAt:now()});activity(D,'User registered',u.email);save(D);return ok(res,{user:sanitize(u)},{'Set-Cookie':setCookie('capital_session',raw,CONFIG.sessionMinutes*60)})}
 if(req.method==='POST'&&p==='/api/auth/login'){const x=await body(req),u=D.users.find(a=>email(a.email)===email(x.email));if(!u||!verifyPassword(x.password,u.passwordHash))return fail(res,401,'INVALID_CREDENTIALS');u.lastLoginAt=now();const raw=crypto.randomBytes(32).toString('hex');D.sessions=D.sessions.filter(s=>new Date(s.expiresAt)>new Date());D.sessions.push({tokenHash:tokenHash(raw),userId:u.id,createdAt:now(),expiresAt:new Date(Date.now()+CONFIG.sessionMinutes*60000).toISOString(),lastActiveAt:now()});save(D);return ok(res,{user:sanitize(u)},{'Set-Cookie':setCookie('capital_session',raw,CONFIG.sessionMinutes*60)})}
 if(req.method==='POST'&&p==='/api/auth/logout'){const c=cookies(req).capital_session;if(c)D.sessions=D.sessions.filter(s=>s.tokenHash!==tokenHash(c));save(D);return ok(res,true,{'Set-Cookie':setCookie('capital_session','',0)})}
 if(req.method==='POST'&&p==='/api/auth/change-password'){const u=requireUser(req,res,D);if(!u)return;const x=await body(req);if(!verifyPassword(x.currentPassword,u.passwordHash))return fail(res,401,'INVALID_CREDENTIALS');if(!String(x.newPassword||'').match(/^.{8,128}$/))return fail(res,400,'INVALID_PASSWORD');u.passwordHash=passwordHash(x.newPassword);save(D);return ok(res,true)}
 if(req.method==='POST'&&p==='/api/admin/auth/login'){const x=await body(req);if(email(x.email)!==ADMIN_EMAIL||String(x.password)!==ADMIN_PASSWORD)return fail(res,401,'INVALID_CREDENTIALS');const raw=crypto.randomBytes(32).toString('hex');D.adminSessions=D.adminSessions.filter(s=>new Date(s.expiresAt)>new Date());D.adminSessions.push({tokenHash:tokenHash(raw),email:ADMIN_EMAIL,role:'owner',createdAt:now(),expiresAt:new Date(Date.now()+8*60*60*1000).toISOString(),lastActiveAt:now()});activity(D,'Admin login',ADMIN_EMAIL);save(D);return ok(res,{email:ADMIN_EMAIL,role:'owner'},{'Set-Cookie':setCookie('capital_admin_session',raw,8*60*60)})}
 if(req.method==='POST'&&p==='/api/admin/auth/logout'){const c=cookies(req).capital_admin_session;if(c)D.adminSessions=D.adminSessions.filter(s=>s.tokenHash!==tokenHash(c));save(D);return ok(res,true,{'Set-Cookie':setCookie('capital_admin_session','',0)})}
 if(req.method==='GET'&&p==='/api/admin/me'){const a=adminAuth(req,D);return a?ok(res,{email:a.email,role:a.role}):fail(res,401,'ADMIN_UNAUTHENTICATED')}
 if(p.startsWith('/api/admin/')){if(!requireAdmin(req,res,D))return;
  if(req.method==='GET'&&p==='/api/admin/dashboard'){return ok(res,{users:D.users.length,available:D.users.reduce((s,u)=>s+Number(u.available||0),0),pendingDeposits:D.deposits.filter(x=>x.status==='pending').length,pendingWithdrawals:D.withdrawals.filter(x=>x.status==='pending').length,recent:D.activities.slice(0,8)})}
  if(req.method==='GET'&&p==='/api/admin/users'){return ok(res,D.users.map(sanitize).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
  let m=p.match(/^\/api\/admin\/users\/([^/]+)$/);if(req.method==='GET'&&m){const u=D.users.find(x=>x.id===decodeURIComponent(m[1]));if(!u)return fail(res,404,'USER_NOT_FOUND');const pending=D.withdrawals.filter(w=>w.userId===u.id&&w.status==='pending').reduce((s,w)=>s+Number(w.amount),0);return ok(res,{user:sanitize(u),team:team(u,D),pendingWithdrawal:pending,lastDeposit:D.deposits.filter(x=>x.userId===u.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))[0]||null})}
  m=p.match(/^\/api\/admin\/users\/([^/]+)\/(password|wallet)$/);if(req.method==='POST'&&m){const u=D.users.find(x=>x.id===decodeURIComponent(m[1]));if(!u)return fail(res,404,'USER_NOT_FOUND');const x=await body(req);if(m[2]==='password'){if(!String(x.password||'').match(/^.{8,128}$/))return fail(res,400,'INVALID_PASSWORD');u.passwordHash=passwordHash(x.password);activity(D,'User password reset',u.email);save(D);return ok(res,true)}if(!wallet(x.address))return fail(res,400,'INVALID_WALLET');u.wallet=String(x.address).trim();activity(D,'User wallet changed',u.email);save(D);return ok(res,sanitize(u))}
  if(req.method==='POST'&&m&&p.startsWith('/api/admin/users/')&&p.endsWith('/status')){const u=D.users.find(x=>x.id===decodeURIComponent(m[1]));if(!u)return fail(res,404,'USER_NOT_FOUND');const x=await body(req);if(!['active','suspended','blocked'].includes(x.status))return fail(res,400,'INVALID_STATUS');u.status=x.status;activity(D,'User status changed',u.email+' → '+x.status);save(D);return ok(res,sanitize(u))}
  if(req.method==='GET'&&p==='/api/admin/deposits')return ok(res,D.deposits.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).map(x=>({...x,user:D.users.find(u=>u.id===x.userId)?.email||x.email})))
  m=p.match(/^\/api\/admin\/deposits\/([^/]+)\/review$/);if(req.method==='POST'&&m){const d=D.deposits.find(x=>x.id===decodeURIComponent(m[1]));if(!d)return fail(res,404,'DEPOSIT_NOT_FOUND');if(d.status!=='pending')return fail(res,409,'ALREADY_REVIEWED');const x=await body(req);if(!['approved','rejected'].includes(x.status))return fail(res,400,'INVALID_STATUS');d.status=x.status;d.verificationStatus=x.status;d.processedAt=now();d.rejectReason=String(x.reason||'');if(x.status==='approved'){const u=D.users.find(a=>a.id===d.userId);if(u){u.balance+=Number(d.amount);u.available+=Number(d.amount);u.investedCapital+=Number(d.amount)}}activity(D,'Deposit reviewed',d.id+' → '+x.status);save(D);return ok(res,d)}
  if(req.method==='GET'&&p==='/api/admin/withdrawals')return ok(res,D.withdrawals.slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))
  m=p.match(/^\/api\/admin\/withdrawals\/([^/]+)\/review$/);if(req.method==='POST'&&m){const w=D.withdrawals.find(x=>x.id===decodeURIComponent(m[1]));if(!w)return fail(res,404,'WITHDRAWAL_NOT_FOUND');if(w.status!=='pending')return fail(res,409,'ALREADY_REVIEWED');const x=await body(req);if(!['approved','rejected'].includes(x.status))return fail(res,400,'INVALID_STATUS');const u=D.users.find(a=>a.id===w.userId);w.status=x.status;w.processedAt=now();w.rejectReason=String(x.reason||'');if(x.status==='approved'&&u){u.available=Math.max(0,u.available-Number(w.amount));u.balance=Math.max(0,u.balance-Number(w.amount));u.totalWithdrawals+=Number(w.amount)}activity(D,'Withdrawal reviewed',w.id+' → '+x.status);save(D);return ok(res,w)}
  if(req.method==='GET'&&p==='/api/admin/transactions'){const tx=[...D.deposits.map(x=>({id:x.id,userId:x.userId,type:'deposit',amount:Number(x.amount),status:x.status,network:x.network,createdAt:x.createdAt})),...D.withdrawals.map(x=>({id:x.id,userId:x.userId,type:'withdrawal',amount:-Number(x.amount),status:x.status,network:x.network,createdAt:x.createdAt}))].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));return ok(res,tx)}
  if(req.method==='GET'&&p==='/api/admin/plans'){return ok(res,Object.entries(CONFIG.plans).map(([vip,p])=>({vip:Number(vip),...p,members:D.users.filter(u=>Number(u.activePlan?.vip)===Number(vip)&&u.activePlan?.status==='active').length})))}
  if(req.method==='GET'&&p==='/api/admin/activity')return ok(res,D.activities)
  if(req.method==='GET'&&p==='/api/admin/announcements')return ok(res,D.announcements)
  if(req.method==='POST'&&p==='/api/admin/announcements'){const x=await body(req);if(!String(x.title||'').trim()||!String(x.body||'').trim())return fail(res,400,'INVALID_ANNOUNCEMENT');const a={id:id('ANN'),title:String(x.title).trim(),body:String(x.body).trim(),status:x.status==='published'?'published':'draft',createdAt:now(),userId:null};D.announcements.unshift(a);activity(D,'Announcement created',a.title);save(D);return ok(res,a)}
  if(req.method==='GET'&&p==='/api/admin/settings')return ok(res,D.settings)
  if(req.method==='POST'&&p==='/api/admin/settings'){const x=await body(req);if(x.adminName!==undefined)D.settings.adminName=String(x.adminName).trim();if(x.timezone!==undefined)D.settings.timezone=String(x.timezone);if(x.deposit){D.settings.deposit={...D.settings.deposit,...x.deposit};}activity(D,'Settings updated','Admin settings');save(D);return ok(res,D.settings)}
  if(req.method==='GET'&&p==='/api/admin/managers')return ok(res,D.adminManagers)
  if(req.method==='POST'&&p==='/api/admin/managers'){const x=await body(req);if(!String(x.name||'').trim()||!email(x.email)||!Array.isArray(x.permissions)||!x.permissions.length)return fail(res,400,'INVALID_MANAGER');if(D.adminManagers.some(m=>email(m.email)===email(x.email)))return fail(res,409,'EMAIL_EXISTS');const m={id:id('MGR'),name:String(x.name).trim(),email:email(x.email),permissions:x.permissions,createdAt:now()};D.adminManagers.push(m);save(D);return ok(res,m)}
  m=p.match(/^\/api\/admin\/managers\/([^/]+)$/);if(req.method==='DELETE'&&m){D.adminManagers=D.adminManagers.filter(x=>x.id!==decodeURIComponent(m[1]));save(D);return ok(res,true)}
  return fail(res,404,'NOT_FOUND');}
 const u=userAuth(req,D);if(!u){if(p.startsWith('/api/'))return fail(res,401,'UNAUTHENTICATED')}else{
  if(req.method==='GET'&&p==='/api/me')return ok(res,sanitize(u));if(req.method==='GET'&&p==='/api/dashboard')return ok(res,dashboard(u,D));if(req.method==='GET'&&p==='/api/profile/team')return ok(res,team(u,D));if(req.method==='GET'&&p==='/api/profile/wallet')return ok(res,u.wallet||'');
  if(req.method==='POST'&&p==='/api/profile/wallet'){const x=await body(req),a=String(x.address||'').trim();if(u.wallet)return fail(res,409,'WALLET_LOCKED');if(!wallet(a))return fail(res,400,'INVALID_WALLET');u.wallet=a;save(D);return ok(res,a)}
  if(req.method==='GET'&&p==='/api/notifications')return ok(res,notifications(u,D));let m=p.match(/^\/api\/notifications\/(.+)\/read$/);if(req.method==='POST'&&m){u.notificationReadIds=[...(u.notificationReadIds||[]),decodeURIComponent(m[1])].filter((v,i,a)=>a.indexOf(v)===i);save(D);return ok(res,true)}
  if(req.method==='GET'&&p==='/api/deposits')return ok(res,D.deposits.filter(x=>x.userId===u.id));if(req.method==='POST'&&p==='/api/deposits'){const x=await body(req),a=amount(x.amount),tx=String(x.txid||'').trim();if(a===null||a<CONFIG.deposit.minAmount)return fail(res,400,'MIN_DEPOSIT');if(tx.length<8||tx.length>256)return fail(res,400,'INVALID_TXID');if(D.deposits.some(d=>String(d.txid).toLowerCase()===tx.toLowerCase()))return fail(res,409,'TXID_EXISTS');const d={id:id('DEP'),userId:u.id,email:u.email,name:u.name,amount:a,txid:tx,currency:CONFIG.deposit.currency,network:CONFIG.deposit.network,toAddress:D.settings.deposit.address||CONFIG.deposit.address,status:'pending',verificationStatus:'pending',createdAt:now(),processedAt:null,rejectReason:''};D.deposits.push(d);activity(D,'Deposit requested',u.email+' '+a);save(D);return ok(res,d)}
  if(req.method==='GET'&&p==='/api/withdrawals')return ok(res,D.withdrawals.filter(x=>x.userId===u.id));if(req.method==='POST'&&p==='/api/withdrawals'){const x=await body(req),a=amount(x.amount),w=String(x.address||u.wallet||'').trim(),pending=D.withdrawals.filter(v=>v.userId===u.id&&v.status==='pending').reduce((s,v)=>s+Number(v.amount),0),available=Math.max(0,Number(u.available)-pending);if(a===null||a<CONFIG.withdrawal.minAmount)return fail(res,400,'MIN_WITHDRAWAL');if(a>available)return fail(res,400,'INSUFFICIENT_BALANCE');if(!wallet(w))return fail(res,400,'INVALID_WALLET');const z={id:id('WDR'),userId:u.id,email:u.email,name:u.name,amount:a,currency:CONFIG.withdrawal.currency,network:CONFIG.withdrawal.network,address:w,status:'pending',createdAt:now(),processedAt:null,txid:'',rejectReason:''};D.withdrawals.push(z);activity(D,'Withdrawal requested',u.email+' '+a);save(D);return ok(res,z)}
  if(req.method==='GET'&&p==='/api/history'){const a=D.deposits.filter(x=>x.userId===u.id).map(x=>({id:x.id,type:'deposit',amount:+x.amount,status:x.status,network:x.network,createdAt:x.createdAt})),b=D.withdrawals.filter(x=>x.userId===u.id).map(x=>({id:x.id,type:'withdraw',amount:-x.amount,status:x.status,network:x.network,createdAt:x.createdAt}));return ok(res,[...a,...b].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
  if(req.method==='POST'&&p==='/api/plans/activate'){const x=await body(req),vip=Number(x.vip),a=Number(x.amount),plan=CONFIG.plans[vip];if(!plan||a!==plan.amount)return fail(res,400,'INVALID_PLAN');if(u.activePlan?.status==='active')return fail(res,409,'PLAN_ACTIVE');if(u.balance<a)return fail(res,400,'INSUFFICIENT_BALANCE');u.balance-=a;u.available=Math.max(0,u.available-a);u.investedCapital+=a;u.activePlan={vip,amount:a,rate:plan.rate,activatedAt:now(),status:'active'};activity(D,'Plan activated',u.email+' VIP '+vip);save(D);return ok(res,u.activePlan)}
 }
 return fail(res,404,'NOT_FOUND');
 }catch(e){console.error(e);return fail(res,500,'SERVER_ERROR')}}
function mime(p){return {'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.json':'application/json'}[path.extname(p).toLowerCase()]||'application/octet-stream'}
const server=http.createServer((req,res)=>{if(req.url.startsWith('/api/'))return api(req,res);let p=url.parse(req.url).pathname;if(p==='/'||p==='')p='/frontend/index.html';if(p==='/index.html')p='/frontend/index.html';if(p==='/admin')p='/admin/';if(p==='/admin/')p='/admin/login.html';const file=path.resolve(ROOT,'.'+p);if(!(file===ROOT||file.startsWith(ROOT+path.sep))||!fs.existsSync(file)||fs.statSync(file).isDirectory())return res.writeHead(404).end('Not found');res.writeHead(200,{'Content-Type':mime(file),'Cache-Control':file.includes('/assets/')?'public,max-age=86400':'no-cache','X-Content-Type-Options':'nosniff'});fs.createReadStream(file).pipe(res)});
server.listen(PORT,()=>console.log(`CAPITAL running at http://localhost:${PORT}`));
