'use strict';
const http=require('http'), fs=require('fs'), path=require('path'), crypto=require('crypto'), url=require('url');
const ROOT=path.resolve(__dirname,'..'), DB_FILE=path.join(__dirname,'db.json');
const PORT=Number(process.env.PORT||8080);
const CONFIG={
  deposit:{network:'TRC20',currency:'USDT',address:'TFLkxFWGRQqS8rdiEbPFPqWrbke7fssf5c',minAmount:100},
  withdrawal:{network:'TRC20',currency:'USDT',minAmount:10},
  plans:{1:100,2:200,3:300,4:400,5:500},
  sessionMinutes:30,
  maxBodyBytes:1e6
};
function now(){return new Date().toISOString()}
function id(p){return p+'-'+Date.now().toString(36)+'-'+crypto.randomBytes(4).toString('hex')}
function email(v){return String(v||'').trim().toLowerCase()}
function db(){if(!fs.existsSync(DB_FILE)) save({version:1,users:[],deposits:[],withdrawals:[],sessions:[],adminAnnouncements:[],meta:{createdAt:now()}}); return JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}
function save(x){const tmp=DB_FILE+'.tmp'; fs.writeFileSync(tmp,JSON.stringify(x,null,2)); fs.renameSync(tmp,DB_FILE)}
function passwordHash(password,salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.scryptSync(String(password),salt,64).toString('hex');return `scrypt$${salt}$${hash}`}
function verifyPassword(password,stored){const [,salt,hash]=String(stored||'').split('$'); if(!salt||!hash)return false; const got=crypto.scryptSync(String(password),salt,64).toString('hex'); return crypto.timingSafeEqual(Buffer.from(got,'hex'),Buffer.from(hash,'hex'))}
function tokenHash(t){return crypto.createHash('sha256').update(t).digest('hex')}
function sanitize(u){if(!u)return null; const x={...u}; delete x.passwordHash; return x}
function referralId(users){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; let v; do{v='CAP-'+Array.from({length:8},()=>alphabet[crypto.randomInt(alphabet.length)]).join('')}while(users.some(u=>u.referralId===v)); return v}
function parseCookies(req){const out={}; for(const p of String(req.headers.cookie||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())} return out}
function auth(req,D){const raw=parseCookies(req).capital_session; if(!raw)return null; const h=tokenHash(raw); const s=D.sessions.find(x=>x.tokenHash===h&&new Date(x.expiresAt)>new Date()); if(!s)return null; s.lastActiveAt=now(); return D.users.find(u=>u.id===s.userId)||null}
function cookie(v,maxAge){return `capital_session=${encodeURIComponent(v)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}`}
function finiteAmount(v){const n=Number(v);return Number.isFinite(n)&&n>0?n:null}
function validTrc20(v){return /^T[1-9A-HJ-NP-Za-km-z]{33}$/.test(String(v||'').trim())}
function headers(){return {
  'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',
  'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin',
  'Permissions-Policy':'camera=(), microphone=(), geolocation=()'
}}
function send(res,status,data,extra={}){const body=JSON.stringify(data);res.writeHead(status,{...headers(),...extra});res.end(body)}
function ok(res,data,headers={}){send(res,200,{data},headers)}
function fail(res,status,code){send(res,status,{code})}
async function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>CONFIG.maxBodyBytes)reject(new Error('BODY_TOO_LARGE'))});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{reject(new Error('INVALID_JSON'))}});req.on('error',reject)})}
function requireAuth(req,res,D){const u=auth(req,D);if(!u){fail(res,401,'UNAUTHENTICATED');return null}return u}
function dashboard(u,D){const pending=D.withdrawals.filter(w=>w.userId===u.id&&w.status==='pending').reduce((s,w)=>s+Number(w.amount||0),0);return {investedCapital:Number(u.investedCapital||0),dailyProfit:Number(u.dailyProfit||0),teamProfit:Number(u.teamProfit||0),totalProfit:Number(u.totalProfit||0),available:Math.max(0,Number(u.available||0)-pending),totalWithdrawals:Number(u.totalWithdrawals||0),balance:Number(u.balance||0),activePlan:u.activePlan||null,notificationReadIds:u.notificationReadIds||[]}}
function team(u,D){const direct=D.users.filter(x=>x.referredBy===u.referralId),seen=new Set(),q=direct.map(x=>x.id);while(q.length){const id=q.shift();if(seen.has(id))continue;seen.add(id);const c=D.users.find(x=>x.id===id);if(c)D.users.filter(x=>x.referredBy===c.referralId).forEach(x=>q.push(x.id))}return {directMembers:direct.length,teamMembers:seen.size}}
function notifications(u,D){const read=new Set(u.notificationReadIds||[]);const ws=D.withdrawals.filter(w=>w.userId===u.id&&['completed','approved','success','rejected'].includes(String(w.status).toLowerCase())).map(w=>{const st=String(w.status).toLowerCase(),i='withdrawal:'+w.id+':'+st;return{id:i,kind:'withdrawal',status:st==='rejected'?'rejected':'success',title:st==='rejected'?'درخواست برداشت رد شد':'درخواست برداشت با موفقیت انجام شد',body:st==='rejected'?(w.rejectReason||'درخواست برداشت شما توسط مدیریت رد شده است.'):'برداشت '+Number(w.amount||0).toFixed(2)+' USDT با موفقیت پردازش شد.',createdAt:w.processedAt||w.createdAt,read:read.has(i)}});const a=D.adminAnnouncements.filter(x=>!x.userId||x.userId===u.id).map(x=>({id:'announcement:'+x.id,kind:'admin',status:'info',title:x.title||'اطلاعیه مدیریت',body:x.body||'',createdAt:x.createdAt||now(),read:read.has('announcement:'+x.id)}));return [...ws,...a].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
async function api(req,res){let D=db(); const p=url.parse(req.url).pathname; try{
 if(req.method==='POST'&&p==='/api/auth/register'){const x=await body(req),em=email(x.email);if(!em||!x.password||String(x.password).length<8||String(x.password).length>128)return fail(res,400,'INVALID_PASSWORD');if(D.users.some(u=>email(u.email)===em))return fail(res,409,'EMAIL_EXISTS');const u={id:id('USR'),referralId:referralId(D.users),name:String(x.name||'').trim(),family:String(x.family||'').trim(),email:em,passwordHash:passwordHash(x.password),status:'active',createdAt:now(),lastLoginAt:now(),wallet:'',referredBy:String(x.referredBy||''),balance:0,available:0,investedCapital:0,dailyProfit:0,teamProfit:0,totalProfit:0,totalWithdrawals:0,activePlan:null,notificationReadIds:[]};D.users.push(u);const raw=crypto.randomBytes(32).toString('hex');D.sessions.push({tokenHash:tokenHash(raw),userId:u.id,createdAt:now(),expiresAt:new Date(Date.now()+CONFIG.sessionMinutes*60000).toISOString(),lastActiveAt:now()});save(D);return ok(res,{user:sanitize(u)},{'Set-Cookie':cookie(raw,CONFIG.sessionMinutes*60)})}
 if(req.method==='POST'&&p==='/api/auth/login'){const x=await body(req),u=D.users.find(a=>email(a.email)===email(x.email));if(!u||typeof x.password!=='string'||x.password.length>128||!verifyPassword(x.password,u.passwordHash))return fail(res,401,'INVALID_CREDENTIALS');u.lastLoginAt=now();const raw=crypto.randomBytes(32).toString('hex');D.sessions=D.sessions.filter(s=>new Date(s.expiresAt)>new Date());D.sessions.push({tokenHash:tokenHash(raw),userId:u.id,createdAt:now(),expiresAt:new Date(Date.now()+CONFIG.sessionMinutes*60000).toISOString(),lastActiveAt:now()});save(D);return ok(res,{user:sanitize(u)},{'Set-Cookie':cookie(raw,CONFIG.sessionMinutes*60)})}
 if(req.method==='POST'&&p==='/api/auth/logout'){const c=parseCookies(req).capital_session;if(c)D.sessions=D.sessions.filter(s=>s.tokenHash!==tokenHash(c));save(D);return ok(res,true,{'Set-Cookie':cookie('',0)})}
 if(req.method==='POST'&&p==='/api/auth/change-password'){const u=requireAuth(req,res,D);if(!u)return;const x=await body(req);if(!verifyPassword(x.currentPassword,u.passwordHash))return fail(res,401,'INVALID_CREDENTIALS');if(String(x.newPassword||'').length<8||String(x.newPassword||'').length>128)return fail(res,400,'INVALID_PASSWORD');u.passwordHash=passwordHash(x.newPassword);save(D);return ok(res,true)}
 const u=requireAuth(req,res,D);if(!u)return;
 if(req.method==='GET'&&p==='/api/me')return ok(res,sanitize(u));
 if(req.method==='GET'&&p==='/api/dashboard')return ok(res,dashboard(u,D));
 if(req.method==='GET'&&p==='/api/profile/team')return ok(res,team(u,D));
 if(req.method==='GET'&&p==='/api/profile/wallet')return ok(res,u.wallet||'');
 if(req.method==='POST'&&p==='/api/profile/wallet'){const x=await body(req),a=String(x.address||'').trim();if(u.wallet)return fail(res,409,'WALLET_LOCKED');if(!a)return fail(res,400,'WALLET_REQUIRED');u.wallet=a;save(D);return ok(res,a)}
 if(req.method==='GET'&&p==='/api/notifications')return ok(res,notifications(u,D));
 let m=p.match(/^\/api\/notifications\/(.+)\/read$/);if(req.method==='POST'&&m){u.notificationReadIds=[...(u.notificationReadIds||[]),decodeURIComponent(m[1])].filter((v,i,a)=>a.indexOf(v)===i);save(D);return ok(res,true)}
 if(req.method==='GET'&&p==='/api/deposits')return ok(res,D.deposits.filter(x=>x.userId===u.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)));
 if(req.method==='POST'&&p==='/api/deposits'){const x=await body(req),amount=finiteAmount(x.amount),txid=String(x.txid||'').trim();if(amount===null||amount<CONFIG.deposit.minAmount||amount>100000000)return fail(res,400,'INVALID_AMOUNT');if(txid.length<8||txid.length>256)return fail(res,400,'INVALID_TXID');if(amount<CONFIG.deposit.minAmount)return fail(res,400,'MIN_DEPOSIT');if(!txid)return fail(res,400,'TXID_REQUIRED');if(D.deposits.some(d=>String(d.txid).toLowerCase()===txid.toLowerCase()))return fail(res,409,'TXID_EXISTS');const item={id:id('DEP'),userId:u.id,email:u.email,name:u.name,amount,txid,currency:CONFIG.deposit.currency,network:CONFIG.deposit.network,toAddress:CONFIG.deposit.address,fromAddress:'',blockNumber:null,confirmations:0,blockchainStatus:'unverified',verificationStatus:'pending',status:'pending',createdAt:now(),verifiedAt:null,rejectedAt:null,rejectReason:''};D.deposits.push(item);save(D);return ok(res,item)}
 if(req.method==='GET'&&p==='/api/withdrawals')return ok(res,D.withdrawals.filter(x=>x.userId===u.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)));
 if(req.method==='POST'&&p==='/api/withdrawals'){const x=await body(req),amount=finiteAmount(x.amount),wallet=String(x.address||u.wallet||'').trim(),pending=D.withdrawals.filter(w=>w.userId===u.id&&w.status==='pending').reduce((s,w)=>s+Number(w.amount||0),0),available=Math.max(0,Number(u.available||0)-pending);if(amount===null||amount>100000000)return fail(res,400,'INVALID_AMOUNT');if(amount<CONFIG.withdrawal.minAmount)return fail(res,400,'MIN_WITHDRAWAL');if(amount>available)return fail(res,400,'INSUFFICIENT_BALANCE');if(!wallet)return fail(res,400,'WALLET_REQUIRED');if(!validTrc20(wallet))return fail(res,400,'INVALID_WALLET');const item={id:id('WDR'),userId:u.id,email:u.email,name:u.name,amount,currency:CONFIG.withdrawal.currency,network:CONFIG.withdrawal.network,address:wallet,status:'pending',blockchainStatus:'not_sent',createdAt:now(),processedAt:null,txid:''};D.withdrawals.push(item);save(D);return ok(res,item)}
 if(req.method==='GET'&&p==='/api/history'){const a=D.deposits.filter(x=>x.userId===u.id).map(x=>({id:x.id,type:'deposit',amount:Number(x.amount||0),status:x.status,network:x.network,createdAt:x.createdAt}));const b=D.withdrawals.filter(x=>x.userId===u.id).map(x=>({id:x.id,type:'withdraw',amount:-Number(x.amount||0),status:x.status,network:x.network,createdAt:x.createdAt}));return ok(res,[...a,...b].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)))}
 if(req.method==='POST'&&p==='/api/plans/activate'){const x=await body(req),amount=finiteAmount(x.amount),vip=Number(x.vip);if(amount===null||!Number.isInteger(vip)||CONFIG.plans[vip]!==amount)return fail(res,400,'INVALID_PLAN');if(Number(u.balance||0)<amount)return fail(res,400,'INSUFFICIENT_BALANCE');if(u.activePlan&&Number(u.activePlan.vip)!==vip)return fail(res,409,'PLAN_ACTIVE');u.activePlan={vip,amount,activatedAt:u.activePlan?.activatedAt||now(),status:'active'};save(D);return ok(res,u.activePlan)}
 return fail(res,404,'NOT_FOUND');
 }catch(e){console.error(e);return fail(res,500,'SERVER_ERROR')}
}
function mime(p){return {'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.json':'application/json'}[path.extname(p).toLowerCase()]||'application/octet-stream'}
const server=http.createServer((req,res)=>{if(req.url.startsWith('/api/'))return api(req,res);let p=url.parse(req.url).pathname;if(p==='/server'||p.startsWith('/server/'))return res.writeHead(404).end('Not found');if(p==='/'||p==='')p='/frontend/index.html';if(p==='/index.html')p='/frontend/index.html';if(p==='/admin')p='/admin/';if(p==='/admin/')p='/admin/login.html';const file=path.resolve(ROOT,'.'+p);if(!(file===ROOT||file.startsWith(ROOT+path.sep))||!fs.existsSync(file)||fs.statSync(file).isDirectory())return res.writeHead(404).end('Not found');res.writeHead(200,{...headers(),'Content-Type':mime(file),'Cache-Control':file.includes('/assets/')?'public, max-age=86400':'no-cache'});fs.createReadStream(file).pipe(res)});
server.listen(PORT,()=>console.log(`CAPITAL v20 running at http://localhost:${PORT}`));
