const TZ = 'Asia/Kabul';
const PLANS = {
  1: { amount: 100, daily: 1.10 },
  2: { amount: 200, daily: 2.40 },
  3: { amount: 300, daily: 3.90 },
  4: { amount: 400, daily: 5.60 },
  5: { amount: 500, daily: 7.50 }
};
const CONFIG = {
  depositAddress: 'TFLkxFWGRQqS8rdiEbPFPQwrbke7fssf5c',
  depositNetwork: 'TRC20',
  depositCurrency: 'USDT',
  withdrawalNetwork: 'TRC20',
  withdrawalCurrency: 'USDT',
  withdrawalFee: 0.10,
  withdrawalWindowStart: 8 * 60,
  withdrawalWindowEnd: 16 * 60,
  minimumRemainingAvailable: 20,
  teamRate: 0.001,
  referralRate: 0.05,
  teamMultiplier: 3,
  sessionMinutes: 30,
  adminSessionMinutes: 60
};
const enc = new TextEncoder();
const dec = new TextDecoder();
const MICRO = 1_000_000;
const json = (x) => JSON.stringify(x ?? {});
const micro = (n) => Math.round(Number(n) * MICRO);
const money = (n) => Math.round(Number(n || 0)) / MICRO;
const now = () => new Date().toISOString();
const id = (prefix) => `${prefix}_${crypto.randomUUID().replaceAll('-', '')}`;
const email = (v) => String(v || '').trim().toLowerCase();
const localParts = (date = new Date()) => {
  const f = new Intl.DateTimeFormat('en-CA', { timeZone: TZ, year:'numeric', month:'2-digit', day:'2-digit', hour:'2-digit', minute:'2-digit', second:'2-digit', hourCycle:'h23' }).formatToParts(date);
  const o={}; for (const p of f) o[p.type]=p.value; return o;
};
const localDateKey = (date = new Date()) => { const p=localParts(date); return `${p.year}-${p.month}-${p.day}`; };
const localMinutes = (date = new Date()) => { const p=localParts(date); return Number(p.hour)*60+Number(p.minute); };
function addLocalDays(key, days) { const [y,m,d]=key.split('-').map(Number); const dt=new Date(Date.UTC(y,m-1,d+days,12)); return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(dt); }
function localDaysBetween(a,b){ const ka=localDateKey(new Date(a)), kb=localDateKey(new Date(b)); const [ay,am,ad]=ka.split('-').map(Number), [by,bm,bd]=kb.split('-').map(Number); return Math.round((Date.UTC(by,bm-1,bd)-Date.UTC(ay,am-1,ad))/86400000); }
function randomIdPart(){ const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; let s=''; const bytes=new Uint8Array(5); crypto.getRandomValues(bytes); for(const b of bytes)s+=alphabet[b%alphabet.length]; return s; }
async function uniqueUserId(db){ for(let i=0;i<20;i++){const x='CAP'+randomIdPart(); const r=await db.prepare('SELECT 1 FROM users WHERE id=?').bind(x).first(); if(!r)return x;} throw new Error('ID_GENERATION_FAILED'); }
function corsHeaders(origin, env){ const allowed=env.ALLOWED_ORIGIN||origin||''; return {'Access-Control-Allow-Origin':allowed,'Access-Control-Allow-Credentials':'true','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'}; }
function headers(origin,env){ return {'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",...corsHeaders(origin,env)}; }
function response(data,status=200,origin='',env={}){ return new Response(JSON.stringify(data),{status,headers:headers(origin,env)}); }
function ok(data,origin,env){return response({data},200,origin,env)}
function fail(code,status=400,origin='',env={},detail){return response({code,...(detail?{detail}: {})},status,origin,env)}
async function body(req){try{return await req.json()}catch{return {}}}
function cookieMap(req){const o={}; for(const p of (req.headers.get('Cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())} return o}
function cookie(name,value,maxAge){return `${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}`}
async function sha256(value){const b=await crypto.subtle.digest('SHA-256',enc.encode(String(value))); return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function randomToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function hashPassword(password,saltHex){const salt=saltHex||await randomToken(); const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']); const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:hexBytes(salt),iterations:150000,hash:'SHA-256'},key,256); return `pbkdf2$${salt}$${hexBytesToString(bits)}`}
function hexBytes(h){const a=new Uint8Array(h.length/2);for(let i=0;i<a.length;i++)a[i]=parseInt(h.slice(i*2,i*2+2),16);return a}
function hexBytesToString(ab){return [...new Uint8Array(ab)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function verifyPassword(password,stored){const [kind,salt,hash]=String(stored||'').split('$');if(kind!=='pbkdf2'||!salt||!hash)return false; const v=await hashPassword(password,salt); return v===stored}
function safeUser(r){if(!r)return null; const u={...r}; for(const k of Object.keys(u))if(k.endsWith('_micro'))u[k.replace('_micro','')]=money(u[k]); return {id:u.id,name:u.name,family:u.family,email:u.email,status:u.status,createdAt:u.created_at,lastLoginAt:u.last_login_at,wallet:u.wallet,referredBy:u.referred_by,balance:u.balance,available:u.available,investedCapital:u.invested_capital,dailyProfit:u.daily_profit,teamProfit:u.team_profit,referralIncome:u.referral_income,totalProfit:u.total_profit,totalWithdrawals:u.total_withdrawals,activePlan:u.active_plan_vip?{vip:u.active_plan_vip,amount:money(u.active_plan_amount_micro),dailyProfit:money(u.active_plan_daily_profit_micro),activatedAt:u.active_plan_activated_at,status:'active'}:null,profitState:u.profit_state,profitEligibleFromDate:u.profit_eligible_from_date,teamProfitEligibleFromDate:u.team_profit_eligible_from_date,capState:u.cap_status?{status:u.cap_status,capAmount:u.cap_amount_micro==null?null:money(u.cap_amount_micro),capUsed:money(u.cap_used_micro),eligibleAt:u.cap_eligible_at,lastChangedAt:u.cap_last_changed_at}:null,referralBonusAmount:money(u.referral_bonus_amount_micro),referralBonusReversed:Boolean(u.referral_bonus_reversed)} }
async function getUser(db,idv){return db.prepare('SELECT * FROM users WHERE id=?').bind(idv).first()}
async function auth(req,env){const raw=cookieMap(req).capital_session;if(!raw)return null;const h=await sha256(raw);const s=await env.DB.prepare('SELECT * FROM sessions WHERE token_hash=? AND expires_at>?').bind(h,now()).first();if(!s)return null;await env.DB.prepare('UPDATE sessions SET last_active_at=?,expires_at=? WHERE token_hash=?').bind(now(),new Date(Date.now()+CONFIG.sessionMinutes*60000).toISOString(),h).run();const u=await getUser(env.DB,s.user_id);return u&&u.status==='active'?u:null}
async function adminAuth(req,env){const raw=cookieMap(req).capital_admin_session;if(!raw)return null;const h=await sha256(raw);return env.DB.prepare('SELECT * FROM admin_sessions WHERE token_hash=? AND expires_at>?').bind(h,now()).first()}
async function audit(db,admin,action,targetId,meta={}){await db.prepare('INSERT INTO audit_logs(id,admin_email,action,target_id,meta_json,created_at) VALUES(?,?,?,?,?,?)').bind(id('AUD'),admin,action,targetId,json(meta),now()).run()}
async function ledger(db,userId,type,amountMicro,ref,meta={}){await db.prepare('INSERT INTO ledger_entries(id,user_id,type,amount_micro,reference_id,meta_json,created_at) VALUES(?,?,?,?,?,?,?)').bind(id('LED'),userId,type,amountMicro,ref,json(meta),now()).run()}
function planForAmount(n){const a=Number(n); for(const [vip,p] of Object.entries(PLANS))if(p.amount===a)return Number(vip); return null}
async function directTeamCapital(db,userId){const r=await db.prepare("SELECT COALESCE(SUM(invested_capital_micro),0) AS v FROM users WHERE referred_by=?").bind(userId).first(); return Number(r?.v||0)}
async function capState(db,u){const principal=Number(u.invested_capital_micro||0), team=await directTeamCapital(db,u.id), threshold=principal*CONFIG.teamMultiplier; return {status:principal>0&&team>=threshold?'NO_CAP':'LIMITED_100',teamCapital:team,threshold}}
async function setCapState(db,u,reason='evaluation'){
  if(!Number(u.invested_capital_micro))return u;
  const next=await capState(db,u), prev=u.cap_status;
  if(prev!==next.status){
    const eligible=next.status==='NO_CAP'; const nextDate=addLocalDays(localDateKey(),1);
    await db.prepare(`UPDATE users SET cap_status=?,cap_amount_micro=?,cap_used_micro=0,cap_eligible_at=?,cap_last_changed_at=?,profit_state=?,profit_eligible_from_date=?,team_profit_eligible_from_date=?,updated_at=? WHERE id=?`).bind(next.status,next.status==='LIMITED_100'?Number(u.invested_capital_micro):null,eligible?now():null,now(),prev==='LIMITED_100'&&eligible?'pending':u.profit_state,prev==='LIMITED_100'&&eligible?nextDate:u.profit_eligible_from_date,prev==='LIMITED_100'&&eligible?nextDate:u.team_profit_eligible_from_date,now(),u.id).run();
    await db.prepare('INSERT INTO cap_history(id,user_id,previous_status,new_status,team_capital_micro,threshold_micro,previous_cap_used_micro,reason,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id('CAP'),u.id,prev,next.status,next.teamCapital,next.threshold,Number(u.cap_used_micro||0),reason,now()).run();
  } else {
    await db.prepare('UPDATE users SET cap_status=?,cap_amount_micro=?,updated_at=? WHERE id=?').bind(next.status,next.status==='LIMITED_100'?Number(u.invested_capital_micro):null,now(),u.id).run();
  }
  return {...u,cap_status:next.status,cap_amount_micro:next.status==='LIMITED_100'?Number(u.invested_capital_micro):null,cap_used_micro:prev!==next.status?0:Number(u.cap_used_micro||0),teamCapital:next.teamCapital,threshold:next.threshold};
}
async function addIncome(db,u,type,amountMicro,ref,meta={}){
  if(amountMicro<=0)return;
  const fields={daily_profit_micro:type==='daily_profit'?amountMicro:0,team_profit_micro:type==='team_profit'?amountMicro:0,referral_income_micro:type==='referral_bonus'?amountMicro:0,total_profit_micro:amountMicro,available_micro:amountMicro,balance_micro:amountMicro};
  await db.prepare(`UPDATE users SET daily_profit_micro=daily_profit_micro+?,team_profit_micro=team_profit_micro+?,referral_income_micro=referral_income_micro+?,total_profit_micro=total_profit_micro+?,available_micro=available_micro+?,balance_micro=balance_micro+?,updated_at=? WHERE id=?`).bind(fields.daily_profit_micro,fields.team_profit_micro,fields.referral_income_micro,fields.total_profit_micro,fields.available_micro,fields.balance_micro,now(),u.id).run();
  await ledger(db,u.id,type,amountMicro,ref,meta);
}
async function reverseReferral(db,inviter,amountMicro,ref,meta){if(amountMicro<=0)return;await db.prepare('UPDATE users SET referral_income_micro=referral_income_micro-?,total_profit_micro=total_profit_micro-?,available_micro=available_micro-?,balance_micro=balance_micro-?,updated_at=? WHERE id=?').bind(amountMicro,amountMicro,amountMicro,amountMicro,now(),inviter.id).run();await ledger(db,inviter.id,'referral_reversal',-amountMicro,ref,meta)}
async function approveDeposit(db,d,admin){
  const u=await getUser(db,d.user_id); if(!u)throw Error('USER_NOT_FOUND'); if(u.status!=='active')throw Error('USER_INACTIVE'); if(u.active_plan_vip||Number(u.invested_capital_micro)>0)throw Error('PLAN_ACTIVE'); const vip=planForAmount(money(d.amount_micro)); if(!vip)throw Error('INVALID_PLAN_AMOUNT'); const p=PLANS[vip];
  const depositDate=localDateKey(new Date(d.created_at)), approvalDate=localDateKey(); const beforeCutoff=localMinutes(new Date(d.created_at))<960; const first=beforeCutoff&&depositDate===approvalDate?approvalDate:addLocalDays(depositDate,1);
  await db.prepare(`UPDATE deposits SET status='approved',verification_status='verified',blockchain_status='verified',verified_at=?,approved_by=? WHERE id=?`).bind(now(),admin,d.id).run();
  await db.prepare(`UPDATE users SET balance_micro=balance_micro+?,invested_capital_micro=?,active_plan_vip=?,active_plan_amount_micro=?,active_plan_daily_profit_micro=?,active_plan_activated_at=?,profit_state=?,profit_eligible_from_date=?,team_profit_eligible_from_date=?,daily_profit_micro=0,team_profit_micro=0,cap_status=NULL,cap_amount_micro=NULL,cap_used_micro=0,updated_at=? WHERE id=?`).bind(Number(d.amount_micro),Number(d.amount_micro),vip,micro(p.amount),micro(p.daily),now(),beforeCutoff&&depositDate===approvalDate?'active':'pending',first,first,now(),u.id).run();
  await ledger(db,u.id,'deposit',Number(d.amount_micro),d.id,{network:d.network,txid:d.txid,originalInvestment:true,vip});
  if(beforeCutoff&&depositDate===approvalDate)await addIncome(db,{id:u.id},'daily_profit',micro(p.daily),`${approvalDate}:daily`,{profitDate:approvalDate,vip,principal:Number(d.amount_micro),sameDayDeposit:true});
  if(u.referred_by){const inv=await getUser(db,u.referred_by);if(inv&&inv.status!=='blocked'&&inv.status!=='suspended'){const bonus=Math.round(Number(d.amount_micro)*CONFIG.referralRate);const rid=id('RFB');await addIncome(db,inv,'referral_bonus',bonus,d.id,{rate:CONFIG.referralRate,inviteeId:u.id,investment:Number(d.amount_micro)});await db.prepare('UPDATE deposits SET referral_bonus_id=?,referral_bonus_amount_micro=?,referral_bonus_recipient=? WHERE id=?').bind(rid,bonus,inv.id,d.id).run();await db.prepare('UPDATE users SET referral_bonus_id=?,referral_bonus_amount_micro=?,referral_bonus_recipient=? WHERE id=?').bind(rid,bonus,inv.id,u.id).run();}}
  await audit(db,admin,'deposit.approve',d.id,{userId:u.id,amount:money(d.amount_micro),vip,firstProfitDay:first});
  const fresh=await getUser(db,u.id); await setCapState(db,fresh,'deposit-approved');
}
async function ensureDaily(db){
  const dateKey=localDateKey(); const meta=await db.prepare("SELECT value FROM system_meta WHERE key='last_daily_run'").first(); if(meta?.value===dateKey)return;
  const pending=await db.prepare("SELECT * FROM withdrawals WHERE status='pending'").all(); for(const w of pending.results){if(localDateKey(new Date(w.created_at))<dateKey){await db.prepare("UPDATE withdrawals SET status='expired',processed_at=? WHERE id=?").bind(now(),w.id).run();await audit(db,'SYSTEM','withdraw.expire',w.id,{reason:'pending crossed Afghanistan financial day'})}}
  const users=(await db.prepare("SELECT * FROM users WHERE status IN ('active','suspended','blocked') AND invested_capital_micro>0").all()).results;
  for(let u of users){u=await getUser(db,u.id); const c=await setCapState(db,u,'daily-evaluation'); u=await getUser(db,u.id); if(u.status!=='active')continue; if(u.profit_state==='pending'&&u.profit_eligible_from_date&&dateKey>=u.profit_eligible_from_date){await db.prepare("UPDATE users SET profit_state='active',updated_at=? WHERE id=?").bind(now(),u.id);u=await getUser(db,u.id)} if(u.cap_status==='LIMITED_100'&&Number(u.cap_used_micro)>=Number(u.cap_amount_micro||0)){await db.prepare("UPDATE users SET profit_state='stopped',updated_at=? WHERE id=?").bind(now(),u.id);continue} if(u.profit_state!=='active')continue; const vip=Number(u.active_plan_vip), p=PLANS[vip]; const exists=await db.prepare("SELECT 1 FROM ledger_entries WHERE user_id=? AND type='daily_profit' AND json_extract(meta_json,'$.profitDate')=?").bind(u.id,dateKey).first(); if(!exists)await addIncome(db,u,'daily_profit',micro(p.daily),`${dateKey}:daily`,{profitDate:dateKey,vip,principal:Number(u.invested_capital_micro)});
    const children=(await db.prepare("SELECT * FROM users WHERE referred_by=? AND status='active' AND invested_capital_micro>0").bind(u.id).all()).results;
    for(const child of children){const start=child.team_profit_eligible_from_date||child.profit_eligible_from_date||dateKey;if(dateKey<start)continue;const v=Math.round(Number(child.invested_capital_micro)*CONFIG.teamRate);if(v<=0)continue;const ex=await db.prepare("SELECT 1 FROM ledger_entries WHERE user_id=? AND type='team_profit' AND json_extract(meta_json,'$.profitDate')=? AND json_extract(meta_json,'$.memberId')=?").bind(u.id,dateKey,child.id).first();if(!ex)await addIncome(db,u,'team_profit',v,`${dateKey}:team:${child.id}`,{profitDate:dateKey,memberId:child.id,memberInvestment:Number(child.invested_capital_micro),rate:CONFIG.teamRate});}
  }
  await db.prepare("INSERT OR REPLACE INTO system_meta(key,value) VALUES('last_daily_run',?)").bind(dateKey).run();
}
async function notifications(db,u){const reads=new Set((await db.prepare('SELECT notification_id FROM notification_reads WHERE user_id=?').bind(u.id).all()).results.map(x=>x.notification_id));const ws=(await db.prepare("SELECT * FROM withdrawals WHERE user_id=? AND status IN ('completed','rejected','expired') ORDER BY created_at DESC").bind(u.id).all()).results.map(w=>({id:'withdrawal:'+w.id,kind:'withdrawal',status:w.status,title:w.status==='rejected'?'Withdrawal rejected':'Withdrawal processed',body:w.status==='rejected'?(w.reject_reason||'Your withdrawal was rejected.'):`Withdrawal ${money(w.amount_micro).toFixed(2)} USDT was processed.`,createdAt:w.processed_at||w.created_at,read:reads.has('withdrawal:'+w.id)}));const an=(await db.prepare("SELECT * FROM announcements WHERE user_id IS NULL OR user_id=? ORDER BY created_at DESC").bind(u.id).all()).results.map(a=>({id:'announcement:'+a.id,kind:'admin',status:'info',title:a.title,body:a.body,createdAt:a.created_at,read:reads.has('announcement:'+a.id)}));return [...ws,...an].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
function validWallet(v){return /^T[1-9A-HJ-NP-Za-km-z]{33}$/.test(String(v||'').trim())}
async function dashboard(db,u){const pending=await db.prepare("SELECT COALESCE(SUM(amount_micro),0) v FROM withdrawals WHERE user_id=? AND status='pending'").bind(u.id).first();const c=await setCapState(db,u,'dashboard');const fresh=await getUser(db,u.id);return {...safeUser(fresh),pendingWithdrawal:money(pending.v),withdrawableAvailable:Math.max(0,money(fresh.available_micro)-money(pending.v)),capStatus:c.status,capAmount:c.status==='LIMITED_100'?money(fresh.invested_capital_micro):null,capUsed:money(fresh.cap_used_micro),teamCapital:money(c.teamCapital),teamThreshold:money(c.threshold)} }
async function userTeam(db,u){const direct=(await db.prepare("SELECT COUNT(*) c,COALESCE(SUM(invested_capital_micro),0) v FROM users WHERE referred_by=? AND status='active'").bind(u.id).first());const seen=new Set(),q=(await db.prepare("SELECT id FROM users WHERE referred_by=? AND status!='blocked' AND status!='suspended'").bind(u.id).all()).results.map(x=>x.id);while(q.length){const x=q.shift();if(seen.has(x))continue;seen.add(x);const kids=(await db.prepare("SELECT id FROM users WHERE referred_by=? AND status!='blocked' AND status!='suspended'").bind(x).all()).results;for(const k of kids)q.push(k.id)}return {directMembers:Number(direct.c||0),teamMembers:seen.size,directTeamCapital:money(direct.v)} }
async function adminLists(db,path){ if(path==='/users'){const rows=(await db.prepare("SELECT * FROM users ORDER BY created_at DESC").all()).results;const out=[];for(const u of rows)if(u.status!=='deleted'){const c=await capState(db,u);out.push({...safeUser(u),directTeamCapital:money(c.teamCapital),capStatus:c.status})}return out} if(path==='/deposits'){return (await db.prepare('SELECT d.*,u.name,u.family,u.email FROM deposits d JOIN users u ON u.id=d.user_id ORDER BY d.created_at DESC').all()).results.map(x=>({...x,amount:money(x.amount_micro)}))} if(path==='/withdrawals'){return (await db.prepare('SELECT w.*,u.name,u.family,u.email FROM withdrawals w JOIN users u ON u.id=w.user_id ORDER BY w.created_at DESC').all()).results.map(x=>({...x,amount:money(x.amount_micro),fee:money(x.fee_micro),netAmount:money(x.net_amount_micro)}))} if(path==='/transactions'){return (await db.prepare('SELECT * FROM ledger_entries ORDER BY created_at DESC LIMIT 500').all()).results.map(x=>({...x,amount:money(x.amount_micro),meta:JSON.parse(x.meta_json||'{}')}))} if(path==='/activity'){return (await db.prepare('SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT 500').all()).results.map(x=>({...x,admin:x.admin_email,targetId:x.target_id,meta:JSON.parse(x.meta_json||'{}')}))} return [] }
async function api(req,env){const url=new URL(req.url),p=url.pathname,origin=req.headers.get('Origin')||''; if(req.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders(origin,env)}); if(!env.DB)return fail('D1_NOT_BOUND',500,origin,env); try{
  if(req.method==='POST'&&p==='/api/auth/register'){const x=await body(req),em=email(x.email);if(!em||!x.password||String(x.password).length<8||String(x.password).length>128)return fail('INVALID_PASSWORD',400,origin,env);if(await env.DB.prepare("SELECT 1 FROM users WHERE email=?").bind(em).first())return fail('EMAIL_EXISTS',409,origin,env);const ref=String(x.referredBy||'').trim().toUpperCase();if(ref&&!/^CAP[A-Z0-9]{5}$/.test(ref))return fail('INVALID_REFERRAL',400,origin,env);if(ref&&!(await getUser(env.DB,ref)))return fail('INVALID_REFERRAL',400,origin,env);const uid=await uniqueUserId(env.DB), ph=await hashPassword(x.password), t=await randomToken(), th=await sha256(t), ts=now(), ex=new Date(Date.now()+CONFIG.sessionMinutes*60000).toISOString();await env.DB.prepare('INSERT INTO users(id,name,family,email,password_hash,status,created_at,last_login_at,referred_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(uid,String(x.name||'').trim(),String(x.family||'').trim(),em,ph,'active',ts,ts,ref||null,ts).run();await env.DB.prepare('INSERT INTO sessions(token_hash,user_id,created_at,expires_at,last_active_at) VALUES(?,?,?,?,?)').bind(th,uid,ts,ex,ts).run();return new Response(JSON.stringify({data:{user:safeUser(await getUser(env.DB,uid))}}),{headers:{...headers(origin,env),'Set-Cookie':cookie('capital_session',t,CONFIG.sessionMinutes*60)}})}
  if(req.method==='POST'&&p==='/api/auth/login'){const x=await body(req),u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email(x.email)).first();if(!u||u.status!=='active'||!(await verifyPassword(String(x.password||''),u.password_hash)))return fail('INVALID_CREDENTIALS',401,origin,env);const t=await randomToken(),h=await sha256(t),ts=now(),ex=new Date(Date.now()+CONFIG.sessionMinutes*60000).toISOString();await env.DB.prepare('UPDATE users SET last_login_at=?,updated_at=? WHERE id=?').bind(ts,ts,u.id).run();await env.DB.prepare('DELETE FROM sessions WHERE user_id=? OR expires_at<=?').bind(u.id,ts).run();await env.DB.prepare('INSERT INTO sessions(token_hash,user_id,created_at,expires_at,last_active_at) VALUES(?,?,?,?,?)').bind(h,u.id,ts,ex,ts).run();return new Response(JSON.stringify({data:{user:safeUser(u)}}),{headers:{...headers(origin,env),'Set-Cookie':cookie('capital_session',t,CONFIG.sessionMinutes*60)}})}
  if(req.method==='POST'&&p==='/api/auth/logout'){const c=cookieMap(req).capital_session;if(c)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(c)).run();return new Response(JSON.stringify({data:true}),{headers:{...headers(origin,env),'Set-Cookie':cookie('capital_session','',0)}})}
  if(req.method==='POST'&&p==='/api/auth/change-password'){const u=await auth(req,env);if(!u)return fail('UNAUTHENTICATED',401,origin,env);const x=await body(req);if(!(await verifyPassword(String(x.currentPassword||''),u.password_hash)))return fail('INVALID_CREDENTIALS',401,origin,env);if(String(x.newPassword||'').length<8)return fail('INVALID_PASSWORD',400,origin,env);await env.DB.prepare('UPDATE users SET password_hash=?,updated_at=? WHERE id=?').bind(await hashPassword(x.newPassword),now(),u.id).run();await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(u.id).run();return ok(true,origin,env)}
  if(req.method==='POST'&&p==='/api/auth/request-reset'){const x=await body(req),u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email(x.email)).first();if(u){const t=await randomToken();await env.DB.prepare('DELETE FROM reset_tokens WHERE user_id=?').bind(u.id).run();await env.DB.prepare('INSERT INTO reset_tokens(token_hash,user_id,created_at,expires_at) VALUES(?,?,?,?)').bind(await sha256(t),u.id,now(),new Date(Date.now()+1800000).toISOString()).run();if(env.RESEND_API_KEY){const base=String(env.PUBLIC_BASE_URL||new URL(req.url).origin).replace(/\/$/,'');const link=`${base}/frontend/reset-password.html?token=${encodeURIComponent(t)}`;await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:env.RESEND_FROM||'CAPITAL <onboarding@resend.dev>',to:[u.email],subject:'CAPITAL password reset',html:`<p>Reset your CAPITAL password:</p><p><a href="${link}">Reset password</a></p><p>This link expires in 30 minutes.</p>`})}).catch(()=>{});}}return ok({message:'If the account exists, a reset link has been sent.'},origin,env)}
  if(req.method==='POST'&&p==='/api/auth/reset-password'){const x=await body(req),s=await env.DB.prepare('SELECT * FROM reset_tokens WHERE token_hash=? AND expires_at>?').bind(await sha256(String(x.token||'')),now()).first();if(!s)return fail('INVALID_RESET_TOKEN',400,origin,env);if(String(x.newPassword||'').length<8)return fail('INVALID_PASSWORD',400,origin,env);await env.DB.prepare('UPDATE users SET password_hash=?,updated_at=? WHERE id=?').bind(await hashPassword(x.newPassword),now(),s.user_id).run();await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(s.user_id).run();await env.DB.prepare('DELETE FROM reset_tokens WHERE token_hash=?').bind(s.token_hash).run();return ok(true,origin,env)}
  if(req.method==='POST'&&p==='/api/admin/login'){const x=await body(req);if(email(x.email)!==email(env.ADMIN_EMAIL)||String(x.password||'')!==String(env.ADMIN_PASSWORD||''))return fail('INVALID_CREDENTIALS',401,origin,env);const t=await randomToken(),h=await sha256(t),ts=now(),ex=new Date(Date.now()+CONFIG.adminSessionMinutes*60000).toISOString();await env.DB.prepare('DELETE FROM admin_sessions WHERE expires_at<=?').bind(ts).run();await env.DB.prepare('INSERT INTO admin_sessions(token_hash,email,created_at,expires_at,last_active_at) VALUES(?,?,?,?,?)').bind(h,email(env.ADMIN_EMAIL),ts,ex,ts).run();return new Response(JSON.stringify({data:{email:email(env.ADMIN_EMAIL)}}),{headers:{...headers(origin,env),'Set-Cookie':cookie('capital_admin_session',t,CONFIG.adminSessionMinutes*60)}})}
  if(req.method==='POST'&&p==='/api/admin/logout'){const c=cookieMap(req).capital_admin_session;if(c)await env.DB.prepare('DELETE FROM admin_sessions WHERE token_hash=?').bind(await sha256(c)).run();return new Response(JSON.stringify({data:true}),{headers:{...headers(origin,env),'Set-Cookie':cookie('capital_admin_session','',0)}})}
  if(p.startsWith('/api/admin/')){const a=await adminAuth(req,env);if(!a)return fail('ADMIN_UNAUTHENTICATED',401,origin,env); if(req.method==='GET'&&p==='/api/admin/me')return ok({email:a.email},origin,env);if(req.method==='GET'&&p==='/api/admin/dashboard'){const [u,d,pd,pw]=await Promise.all([env.DB.prepare("SELECT COUNT(*) c FROM users WHERE status!='blocked'").first(),env.DB.prepare("SELECT COALESCE(SUM(available_micro),0) v FROM users WHERE status!='blocked'").first(),env.DB.prepare("SELECT COUNT(*) c FROM deposits WHERE status='pending'").first(),env.DB.prepare("SELECT COUNT(*) c FROM withdrawals WHERE status='pending'").first()]);return ok({users:Number(u.c),available:money(d.v),pendingDeposits:Number(pd.c),pendingWithdrawals:Number(pw.c)},origin,env)} if(req.method==='GET'&&p==='/api/admin/users')return ok(await adminLists(env.DB,'/users'),origin,env);if(req.method==='GET'&&p==='/api/admin/deposits')return ok(await adminLists(env.DB,'/deposits'),origin,env);if(req.method==='GET'&&p==='/api/admin/withdrawals')return ok(await adminLists(env.DB,'/withdrawals'),origin,env);if(req.method==='GET'&&p==='/api/admin/transactions')return ok(await adminLists(env.DB,'/transactions'),origin,env);if(req.method==='GET'&&p==='/api/admin/activity')return ok(await adminLists(env.DB,'/activity'),origin,env);if(req.method==='GET'&&p==='/api/admin/cap-history')return ok((await env.DB.prepare('SELECT * FROM cap_history ORDER BY created_at DESC LIMIT 500').all()).results.map(x=>({...x,teamCapital:money(x.team_capital_micro),threshold:money(x.threshold_micro),previousCapUsed:money(x.previous_cap_used_micro)})),origin,env);
    let m=p.match(/^\/api\/admin\/deposits\/([^/]+)\/(approve|reject)$/);if(req.method==='POST'&&m){const d=await env.DB.prepare('SELECT * FROM deposits WHERE id=?').bind(decodeURIComponent(m[1])).first();if(!d)return fail('NOT_FOUND',404,origin,env);if(d.status!=='pending')return fail('ALREADY_PROCESSED',409,origin,env);const x=await body(req);if(m[2]==='reject'){await env.DB.prepare("UPDATE deposits SET status='rejected',verification_status='rejected',reject_reason=?,rejected_at=? WHERE id=?").bind(String(x.reason||''),now(),d.id).run();await audit(env.DB,a.email,'deposit.reject',d.id,{reason:String(x.reason||'')});return ok(await env.DB.prepare('SELECT * FROM deposits WHERE id=?').bind(d.id).first(),origin,env)}await approveDeposit(env.DB,d,a.email);return ok(await env.DB.prepare('SELECT * FROM deposits WHERE id=?').bind(d.id).first(),origin,env)}
    m=p.match(/^\/api\/admin\/withdrawals\/([^/]+)\/(approve|reject)$/);if(req.method==='POST'&&m){const w=await env.DB.prepare('SELECT * FROM withdrawals WHERE id=?').bind(decodeURIComponent(m[1])).first();if(!w)return fail('NOT_FOUND',404,origin,env);if(w.status!=='pending')return fail('ALREADY_PROCESSED',409,origin,env);const x=await body(req),u=await getUser(env.DB,w.user_id);if(m[2]==='reject'){await env.DB.prepare("UPDATE withdrawals SET status='rejected',processed_at=?,reject_reason=? WHERE id=?").bind(now(),String(x.reason||''),w.id).run();await audit(env.DB,a.email,'withdraw.reject',w.id,{reason:String(x.reason||'')});return ok(true,origin,env)}const gross=Number(w.amount_micro),fee=Math.round(gross*CONFIG.withdrawalFee),net=gross-fee;const c=await capState(env.DB,u);let used=Number(u.cap_used_micro||0);if(c.status==='LIMITED_100'&&used+gross>Number(u.invested_capital_micro))return fail('WITHDRAWAL_CAP_REACHED',400,origin,env);await env.DB.prepare('UPDATE users SET available_micro=available_micro-?,balance_micro=MAX(0,balance_micro-?),total_withdrawals_micro=total_withdrawals_micro+?,cap_used_micro=CASE WHEN cap_status=\'LIMITED_100\' THEN cap_used_micro+? ELSE cap_used_micro END,profit_state=CASE WHEN cap_status=\'LIMITED_100\' AND cap_used_micro+?>=invested_capital_micro THEN \'stopped\' ELSE profit_state END,updated_at=? WHERE id=?').bind(gross,gross,gross,gross,gross,now(),u.id).run();await env.DB.prepare("UPDATE withdrawals SET status='completed',blockchain_status='manual_pending',fee_micro=?,net_amount_micro=?,txid=?,processed_at=? WHERE id=?").bind(fee,net,String(x.txid||''),now(),w.id).run();await ledger(env.DB,u.id,'withdrawal',-gross,w.id,{fee:money(fee),netAmount:money(net),txid:String(x.txid||''),capStatus:c.status});await audit(env.DB,a.email,'withdraw.approve',w.id,{fee:money(fee),netAmount:money(net),txid:String(x.txid||''),capStatus:c.status});return ok(await env.DB.prepare('SELECT * FROM withdrawals WHERE id=?').bind(w.id).first(),origin,env)}
    if(req.method==='GET'&&p==='/api/admin/user'){const idv=new URL(req.url).searchParams.get('id')||'';const u=await getUser(env.DB,idv);if(!u)return fail('USER_NOT_FOUND',404,origin,env);const deps=(await env.DB.prepare('SELECT * FROM deposits WHERE user_id=? ORDER BY created_at DESC').bind(u.id).all()).results;const last=deps[0];const pend=await env.DB.prepare("SELECT COALESCE(SUM(amount_micro),0) v FROM withdrawals WHERE user_id=? AND status='pending'").bind(u.id).first();const team=await userTeam(env.DB,u);const c=await capState(env.DB,u);return ok({...safeUser(u),lastDeposit:last?{...last,amount:money(last.amount_micro)}:null,lastDepositTxid:last?.txid||'',directTeamCapital:team.directTeamCapital,teamStats:team,capState:{...c,capAmount:c.status==='LIMITED_100'?money(u.invested_capital_micro):null,capUsed:money(u.cap_used_micro)},capHistory:(await env.DB.prepare('SELECT * FROM cap_history WHERE user_id=? ORDER BY created_at DESC').bind(u.id).all()).results,pendingWithdrawal:money(pend.v),withdrawableAvailable:Math.max(0,money(u.available_micro)-money(pend.v))},origin,env)}
    if(req.method==='POST'&&p==='/api/admin/user/status'){const x=await body(req),u=await getUser(env.DB,String(x.userId));if(!u)return fail('USER_NOT_FOUND',404,origin,env);const st=String(x.status||'').toLowerCase();if(!['active','suspended','blocked','deleted'].includes(st))return fail('INVALID_STATUS',400,origin,env);const old=u.status;if(st==='deleted'){if(u.referred_by&&Number(u.referral_bonus_amount_micro)>0&&!u.referral_bonus_reversed&&localDaysBetween(u.created_at,now())<30){const inv=await getUser(env.DB,u.referred_by);if(inv)await reverseReferral(env.DB,inv,Number(u.referral_bonus_amount_micro),u.referral_bonus_id||u.id,{reason:'child-deleted-before-30-days',inviteeId:u.id});}await env.DB.prepare('DELETE FROM audit_logs WHERE target_id=?').bind(u.id).run();await env.DB.prepare('DELETE FROM users WHERE id=?').bind(u.id).run();await audit(env.DB,a.email,'user.delete',u.id,{});return ok({status:'deleted'},origin,env)} if(st!=='active'){await env.DB.prepare("UPDATE users SET status=?,profit_state='stopped',updated_at=? WHERE id=?").bind(st,now(),u.id).run()}else if(old!=='active'&&u.active_plan_vip){await env.DB.prepare("UPDATE users SET status='active',profit_state='pending',profit_eligible_from_date=?,team_profit_eligible_from_date=?,updated_at=? WHERE id=?").bind(addLocalDays(localDateKey(),1),addLocalDays(localDateKey(),1),now(),u.id).run()}else await env.DB.prepare("UPDATE users SET status='active',updated_at=? WHERE id=?").bind(now(),u.id).run();await audit(env.DB,a.email,'user.status',u.id,{from:old,to:st});return ok({status:st},origin,env)}
    if(req.method==='POST'&&p==='/api/admin/user/wallet'){const x=await body(req),u=await getUser(env.DB,String(x.userId));if(!u)return fail('USER_NOT_FOUND',404,origin,env);if(!validWallet(x.address))return fail('INVALID_WALLET',400,origin,env);await env.DB.prepare('UPDATE users SET wallet=?,updated_at=? WHERE id=?').bind(String(x.address).trim(),now(),u.id).run();await audit(env.DB,a.email,'user.wallet-change',u.id,{});return ok({wallet:String(x.address).trim()},origin,env)}
    if(req.method==='POST'&&p==='/api/admin/user/reset-password'){const x=await body(req),u=await getUser(env.DB,String(x.userId));if(!u)return fail('USER_NOT_FOUND',404,origin,env);if(String(x.password||'').length<8)return fail('INVALID_PASSWORD',400,origin,env);await env.DB.prepare('UPDATE users SET password_hash=?,updated_at=? WHERE id=?').bind(await hashPassword(x.password),now(),u.id).run();await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(u.id).run();await audit(env.DB,a.email,'user.password-reset',u.id,{});return ok(true,origin,env)}
    if(req.method==='POST'&&p==='/api/admin/announcements'){const x=await body(req);if(!x.title||!x.body)return fail('INVALID_ANNOUNCEMENT',400,origin,env);const aid=id('ANN');await env.DB.prepare('INSERT INTO announcements(id,title,body,created_at) VALUES(?,?,?,?)').bind(aid,String(x.title),String(x.body),now()).run();await audit(env.DB,a.email,'announcement.create',aid,{});return ok({id:aid},origin,env)}
    return fail('NOT_FOUND',404,origin,env); }
  const u=await auth(req,env); if(!u)return fail('UNAUTHENTICATED',401,origin,env);
  if(req.method==='GET'&&p==='/api/me')return ok(safeUser(u),origin,env);
  if(req.method==='GET'&&p==='/api/dashboard')return ok(await dashboard(env.DB,u),origin,env);
  if(req.method==='GET'&&p==='/api/profile/team')return ok(await userTeam(env.DB,u),origin,env);
  if(req.method==='GET'&&p==='/api/profile/wallet')return ok(u.wallet||'',origin,env);
  if(req.method==='POST'&&p==='/api/profile/wallet'){if(u.wallet)return fail('WALLET_LOCKED',409,origin,env);const x=await body(req);if(!validWallet(x.address))return fail('INVALID_WALLET',400,origin,env);await env.DB.prepare('UPDATE users SET wallet=?,updated_at=? WHERE id=?').bind(String(x.address).trim(),now(),u.id).run();return ok(String(x.address).trim(),origin,env)}
  if(req.method==='GET'&&p==='/api/notifications')return ok(await notifications(env.DB,u),origin,env);
  const nm=p.match(/^\/api\/notifications\/(.+)\/read$/);if(req.method==='POST'&&nm){await env.DB.prepare('INSERT OR REPLACE INTO notification_reads(user_id,notification_id,read_at) VALUES(?,?,?)').bind(u.id,decodeURIComponent(nm[1]),now()).run();return ok(true,origin,env)}
  if(req.method==='GET'&&p==='/api/deposits')return ok((await env.DB.prepare('SELECT * FROM deposits WHERE user_id=? ORDER BY created_at DESC').bind(u.id).all()).results.map(x=>({...x,amount:money(x.amount_micro)})),origin,env);
  if(req.method==='POST'&&p==='/api/deposits'){if(u.active_plan_vip||Number(u.invested_capital_micro)>0)return fail('PLAN_ACTIVE',409,origin,env);if((await env.DB.prepare("SELECT 1 FROM deposits WHERE user_id=? AND status='pending'").bind(u.id).first()))return fail('DEPOSIT_PENDING',409,origin,env);const x=await body(req),a=Number(x.amount),tx=String(x.txid||'').trim();if(![100,200,300,400,500].includes(a))return fail('INVALID_PLAN_AMOUNT',400,origin,env);if(tx.length<8||tx.length>256)return fail('INVALID_TXID',400,origin,env);if(await env.DB.prepare('SELECT 1 FROM deposits WHERE lower(txid)=lower(?)').bind(tx).first())return fail('TXID_EXISTS',409,origin,env);const d={id:id('DEP'),user_id:u.id,amount_micro:micro(a),txid:tx,currency:'USDT',network:'TRC20',to_address:CONFIG.depositAddress,status:'pending',verification_status:'pending',blockchain_status:'unverified',created_at:now(),verified_at:null,rejected_at:null,reject_reason:'',approved_by:null,referral_bonus_id:null,referral_bonus_amount_micro:0,referral_bonus_recipient:null};await env.DB.prepare('INSERT INTO deposits(id,user_id,amount_micro,txid,currency,network,to_address,status,verification_status,blockchain_status,created_at,verified_at,rejected_at,reject_reason) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(d.id,d.user_id,d.amount_micro,d.txid,d.currency,d.network,d.to_address,d.status,d.verification_status,d.blockchain_status,d.created_at,null,null,'').run();return ok({...d,amount:a},origin,env)}
  if(req.method==='GET'&&p==='/api/withdrawals')return ok((await env.DB.prepare('SELECT * FROM withdrawals WHERE user_id=? ORDER BY created_at DESC').bind(u.id).all()).results.map(x=>({...x,amount:money(x.amount_micro),fee:money(x.fee_micro),netAmount:money(x.net_amount_micro)})),origin,env);
  if(req.method==='POST'&&p==='/api/withdrawals'){const x=await body(req),a=Number(x.amount),wallet=String(x.address||u.wallet||'').trim();if(!Number.isFinite(a)||a<=0)return fail('INVALID_AMOUNT',400,origin,env);const today=localDateKey();if(await env.DB.prepare("SELECT 1 FROM withdrawals WHERE user_id=? AND substr(created_at,1,10)=? ").bind(u.id,today).first())return fail('ONE_WITHDRAWAL_PER_DAY',409,origin,env);const pending=await env.DB.prepare("SELECT COALESCE(SUM(amount_micro),0) v FROM withdrawals WHERE user_id=? AND status='pending'").bind(u.id).first();const avail=Number(u.available_micro)-Number(pending.v||0);const min={1:10,2:20,3:30,4:40,5:50}[Number(u.active_plan_vip)]||10;if(a<min)return fail('MIN_WITHDRAWAL',400,origin,env);if(micro(a)>avail)return fail('INSUFFICIENT_BALANCE',400,origin,env);if(money(avail-micro(a))<CONFIG.minimumRemainingAvailable)return fail('MINIMUM_REMAINING_BALANCE',400,origin,env);const c=await capState(env.DB,u);const capUsed=Number(u.cap_used_micro||0);if(c.status==='LIMITED_100'&&capUsed+micro(a)>Number(u.invested_capital_micro))return fail('WITHDRAWAL_CAP_REACHED',400,origin,env);if(localMinutes()<CONFIG.withdrawalWindowStart||localMinutes()>CONFIG.withdrawalWindowEnd)return fail('WITHDRAWAL_WINDOW_CLOSED',400,origin,env);if(!validWallet(wallet))return fail('INVALID_WALLET',400,origin,env);const w={id:id('WDR'),user_id:u.id,amount_micro:micro(a),currency:'USDT',network:'TRC20',address:wallet,status:'pending',blockchain_status:'not_sent',fee_micro:0,net_amount_micro:0,txid:'',created_at:now(),processed_at:null,reject_reason:''};await env.DB.prepare('INSERT INTO withdrawals(id,user_id,amount_micro,currency,network,address,status,blockchain_status,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(w.id,w.user_id,w.amount_micro,w.currency,w.network,w.address,w.status,w.blockchain_status,w.created_at).run();return ok({...w,amount:a},origin,env)}
  if(req.method==='GET'&&p==='/api/history')return ok((await env.DB.prepare('SELECT * FROM ledger_entries WHERE user_id=? ORDER BY created_at DESC').bind(u.id).all()).results.map(x=>({id:x.id,type:x.type,amount:money(x.amount_micro),status:'completed',createdAt:x.created_at,referenceId:x.reference_id,meta:JSON.parse(x.meta_json||'{}')})),origin,env);
  if(req.method==='POST'&&p==='/api/plans/activate')return fail('PLAN_ACTIVATED_BY_DEPOSIT',400,origin,env);
  return fail('NOT_FOUND',404,origin,env);
 }catch(e){console.error(e);return fail('SERVER_ERROR',500,origin,env,e.message)} }

export default { async fetch(req,env,ctx){const url=new URL(req.url);if(url.pathname.startsWith('/api/'))return api(req,env);if(req.method==='GET'&&url.pathname==='/')return env.ASSETS.fetch(new Request(new URL('/frontend/index.html',req.url),req));if(req.method==='GET'&&url.pathname==='/admin')return env.ASSETS.fetch(new Request(new URL('/admin/login.html',req.url),req));return env.ASSETS.fetch(req)}, async scheduled(event,env,ctx){ctx.waitUntil(ensureDaily(env.DB))} };
